Repository NemanjaSimic/Outage-Management-System, pull requests merged in 2020-03, with the labels that each got.

#36 Oms/validate resolve
  OMS-Angular/src/app/modules/graph/components/graph/graph.component.ts
  OMS-Angular/src/app/modules/graph/outage-lifecycle/contents.ts
  OMS-Angular/src/app/modules/graph/outage-lifecycle/tooltip.ts
  OMS-Angular/src/app/shared/models/outage.model.ts
  OMS.Web/OMS.Web.API/Controllers/OutageController.cs
  OMS.Web/OMS.Web.Services/Handlers/OutageLifecycleCommandHandler.cs
  OMS.Web/OMS.Web.Services/Handlers/OutageQueryHandler.cs
  OMS.Web/OMS.Web.Services/Handlers/SwitchCommandHandler.cs
  OMS.Web/OMS.Web.Services/Handlers/TopologyQueryHandler.cs
  OMS.Web/OMS.Web.UI.Models/OutageLifecycleState.cs
  OutageManagementSystem/CalculationEngineService/Topology/TopologyProvider.cs
  OutageManagementSystem/Common/OutageService/Interface/IOutageTopologyModel.cs
  OutageManagementSystem/Common/ServiceContracts/OMS/IOutageSimulatorContract.cs
  OutageManagementSystem/Common/ServiceProxies/Outage/OutageSimulatorServiceProxy.cs
  OutageManagementSystem/OutageManagementService/OMSTestClient/Program.cs
  OutageManagementSystem/OutageManagementService/OutageDatabase/App.config
  OutageManagementSystem/OutageManagementService/OutageManagementService/OutageModel.cs
  OutageManagementSystem/OutageManagementService/OutageSimulator/Services/OutageSimulatorService.cs
  OutageManagementSystem/OutageManagementService/OutageSimulator/UserControls/GenerateOutage.xaml.cs
  OutageManagementSystem/OutageManagementService/OutageSimulator/UserControls/Overview.xaml.cs
  OutageManagementSystem/PubSubEngine/PubSubEngine/Subscriber.cs
Labels: feature

#44 Fix Angular Material
  OMS-Angular/angular.json
  OMS-Angular/package-lock.json
  OMS-Angular/package.json
  OMS-Angular/src/app/app.component.css
  OMS-Angular/src/app/app.component.html
  OMS-Angular/src/app/app.module.ts
  OMS-Angular/src/app/modules/active-browser/active-browser.component.css
  OMS-Angular/src/app/modules/active-browser/active-browser.component.html
  OMS-Angular/src/app/modules/active-browser/active-browser.component.ts
  OMS-Angular/src/app/modules/archived-browser/archived-browser.component.css
  OMS-Angular/src/app/modules/archived-browser/archived-browser.component.html
  OMS-Angular/src/app/modules/archived-browser/archived-browser.component.ts
  OMS-Angular/src/app/modules/graph/components/graph/graph.component.css
  OMS-Angular/src/app/modules/graph/components/graph/graph.component.html
  OMS-Angular/src/app/modules/graph/components/graph/graph.component.ts
  OMS-Angular/src/app/modules/modal/modal.component.css
  OMS-Angular/src/app/modules/modal/modal.component.html
  OMS-Angular/src/app/modules/modal/modal.component.ts
  OMS-Angular/src/app/modules/report/components/report-chart/report-chart.component.css
  OMS-Angular/src/app/modules/report/components/report-chart/report-chart.component.html
  OMS-Angular/src/app/modules/report/components/report-chart/report-chart.component.spec.ts
  OMS-Angular/src/app/modules/report/components/report-chart/report-chart.component.ts
  OMS-Angular/src/app/modules/report/components/report-form/report-form.component.css
  OMS-Angular/src/app/modules/report/components/report-form/report-form.component.html
  OMS-Angular/src/app/modules/report/components/report-form/report-form.component.spec.ts
  OMS-Angular/src/app/modules/report/components/report-form/report-form.component.ts
  OMS-Angular/src/app/modules/report/components/report/report.component.css
  OMS-Angular/src/app/modules/report/components/report/report.component.html
  OMS-Angular/src/app/modules/report/components/report/report.component.spec.ts
  OMS-Angular/src/app/modules/report/components/report/report.component.ts
  OMS-Angular/src/app/modules/report/report.module.ts
  OMS-Angular/src/app/modules/routing/routes.declaration.ts
  OMS-Angular/src/app/modules/routing/routing.module.ts
  OMS-Angular/src/app/services/environment/environment.service.ts
  OMS-Angular/src/app/shared/components/active-outage-modal/active-outage-modal.component.css
  OMS-Angular/src/app/shared/components/active-outage-modal/active-outage-modal.component.html
  OMS-Angular/src/app/shared/components/active-outage-modal/active-outage-modal.component.spec.ts
  OMS-Angular/src/app/shared/components/active-outage-modal/active-outage-modal.component.ts
  OMS-Angular/src/app/shared/components/archived-outage-modal/archived-outage-modal.component.css
  OMS-Angular/src/app/shared/components/archived-outage-modal/archived-outage-modal.component.html
  OMS-Angular/src/app/shared/components/archived-outage-modal/archived-outage-modal.component.spec.ts
  OMS-Angular/src/app/shared/components/archived-outage-modal/archived-outage-modal.component.ts
  OMS-Angular/src/app/shared/components/refresh-menu/refresh-menu.component.css
  OMS-Angular/src/app/shared/components/refresh-menu/refresh-menu.component.html
  OMS-Angular/src/app/shared/components/refresh-menu/refresh-menu.component.spec.ts
  OMS-Angular/src/app/shared/components/refresh-menu/refresh-menu.component.ts
  OMS-Angular/src/app/shared/components/splash/splash.component.css
  OMS-Angular/src/app/shared/models/outage.model.ts
  OMS-Angular/src/app/shared/shared.module.ts
  OMS-Angular/src/index.html
  OMS-Angular/src/main.ts
  OMS-Angular/src/styles.css
Labels: feature, fix

#47 Fix update outages bug
  OMS-Angular/src/app/modules/graph/components/graph/graph.component.ts
Labels: fix

#49 Snackbar notification
  OMS-Angular/package-lock.json
  OMS-Angular/package.json
  OMS-Angular/src/app/app.module.ts
  OMS-Angular/src/app/modules/report/components/report-chart/data.mock.ts
  OMS-Angular/src/app/modules/report/components/report-chart/report-chart.component.html
  OMS-Angular/src/app/modules/report/components/report-chart/report-chart.component.ts
  OMS-Angular/src/app/modules/report/components/report-form/report-form.component.css
  OMS-Angular/src/app/modules/report/components/report-form/report-form.component.html
  OMS-Angular/src/app/modules/report/components/report-form/report-form.component.ts
  OMS-Angular/src/app/modules/report/components/report/report.component.css
  OMS-Angular/src/app/modules/report/components/report/report.component.html
  OMS-Angular/src/app/modules/report/components/report/report.component.ts
  OMS-Angular/src/app/modules/report/report.module.ts
  OMS-Angular/src/app/services/notification/snackbar.service.spec.ts
  OMS-Angular/src/app/services/notification/snackbar.service.ts
  OMS-Angular/src/app/shared/shared.module.ts
  OMS-Angular/src/styles.css
Labels: feature
